language: common-lisp
sudo: false

env:
  global:
    - PATH: $HOME/.roswell/bin:$PATH
    - ROSWELL_INSTALL_DIR: $HOME/.roswell
    - COVERAGE_EXCLUDE: t:roswell
  matrix:
    - LISP=sbcl-bin COVERALLS=true
    - LISP=ccl-bin
    - LISP=abcl
    - LISP=clisp
    - LISP=ecl
    - LISP=alisp

install:
  - curl -L https://raw.githubusercontent.com/roswell/roswell/release/scripts/install-for-ci.sh | sh
  - ros install prove

script:
  - run-prove inquisitor-test.asd
